import './css/style.css'

import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import { Providers } from './providers'
import ReactQueryProvider from '@/react-query'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const aspekta = localFont({
  src: [
    {
      path: '../public/fonts/Aspekta-700.woff2',
      weight: '700',
    },       
  ],
  variable: '--font-aspekta',
  display: 'swap',  
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${aspekta.variable} font-inter antialiased bg-slate-900 text-slate-200 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
        <Providers>
           <ClerkProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
          </ClerkProvider>
        </Providers>
        </div>
      </body>
    </html>
  )
}
